### PR TITLE
Freeze top-level packages at arbitrary existing versions

### PR DESCRIPTION
**Pull request by yuvipanda**
We have not updated this image in ages, and when we just bumped up a couple of
packages (https://github.com/2i2c-org/2i2c-hubs-image/pull/3), it actually bumped up a *lot* of other packages to newer versions. This will break a lot of users in the middle of a semester, which is problematic.

Ideally, we should have 'proper' pinning (like in
https://github.com/CryoInTheCloud/hub-image), but given the lack of that, I have just specifically pinned the versions to what we currently have while we work on a longer term solution.

### CODE REVIEW

**Comment by yuvipanda** [comment]
This kinda pinning sucks! It's better than not pinning, so as to not break stuff

**Comment by damianavila** [comment]
> Ideally, we should have 'proper' pinning

With "proper pinning" you are talking about the conda-lock stuff?

**Comment by yuvipanda** [comment]
@damianavila something like that. needs work and research haha :)

**Review by damianavila — APPROVED** [review]
I know some people are actually against pinning everything but I found that practice, in the past, pragmatically useful in the "educational" field (and less painful than having everything without specific versions).

**Comment by yuvipanda** [comment]
@damianavila I think there shouldn't be pinning at the *library* level, but should be at the *deployment* level (ie in the image itself) - so I think this is the right location for pinning!

**Comment by damianavila** [comment]
> I think there shouldn't be pinning at the library level

When you said a "library level", what you are refering to?

**Comment by yuvipanda** [comment]
@damianavila in a `setup.py`, like https://github.com/executablebooks/jupyter-book/issues/1351

**Comment by damianavila** [comment]
Ah.... yep, I totally concur!!!

**Pull request merged**
